### ISSUE TITLE
collaboration

### ISSUE THREAD

**Issue by RSimmz98** [temycodes/MERN#1]
Hello how are you can we work together on the next project.. we can find something to create together 🛴

**Comment by temisan0x** [comment]
Hey @RSimmz98, I am good. I hope you're too. In regards to working together on a project, I am down with you. We can talk better on Twitter. here's my Twitter handle @daTemyCode.
Best regards.

**Comment by RSimmz98** [comment]
I sent you a request just now lifeisdev is my username
